---
title: "À propos"
about:
  template: jolla
  links: 
    - icon: github
      text: Github
      href: https://github.com/LeoMaurice
---

Crédit : **Léopold MAURICE**, ENSAE, Master Sociologie Quantitative, Démographie (Université Paris-Saclay/UVSQ), Centre Maurice Halbwachs (CMH).

**Thème du Mémoire** : Mémoire de recherche sur le Comité Consultatif National d'Éthique (CCNE), analysant les dynamiques des publications au cours du temps.

**Encadrement** : Sous la direction d'Emmanuel Didier (CMH) et de Samuel Coavoux (ENSAE.

**Année** : Réalisation : 2023-2024.

**Objectif du Site** : Ce site présente les résultats et les annexes numériques de mon mémoire, ainsi que des outils interactifs pour explorer les données.

**Remerciements** : 
Je tiens à exprimer ma gratitude aux personnes suivantes, sans qui ce mémoire n'aurait pas
été possible :

- A **Emmanuel Didier**, que je remercie chaleureusement pour le temps précieux qu'il a consacré à me guider et à m'encourager tout au long de ce projet. Je lui suis particulièrement reconnaissant des ressources financières qu’il a consacré pour le modèle de langage utilisé.

- A **Samuel *Coavoux**, pour son aide précieuse en particulier sur l’usage des LLM et ses retours constructifs, qui ont grandement contribué à l'amélioration de mon travail. Je le remercie tout particulièrement pour m’avoir donné accès à ActiveTigger et ses ressources huma-num.

- A Ivayloa Petev et mes camarades du suivi de mémoire du Master SQD, pour leurs retours constants et leur soutien tout au long de l'année.
- A Joël Laillier et Christian Topalov pour m’avoir donné les informations disponibles sur les membres du CCNE dans la base Qui Gouverne la Science.

- A Thomas Amossé, pour son retour perspicace sur mon rendu de socio-histoire de la statistique, qui a enrichi ma réflexion et affiné mon analyse.

- Un grand merci également aux différents masterants, doctorants et membres de l'équipe autour d'Emmanuel Didier pour les discussions stimulantes et enrichissantes tout au long de l'année. Leur soutien et leurs conseils ont été inestimables.

**Liens Utiles** : Pour plus d'informations sur mes travaux, vous pouvez consulter mon [profil Github](https://github.com/LeoMaurice).
