---
title: "CCNE Descriptive figures"
author: "Léopold MAURICE, ENSAE"
date: "2024-02-29"
project: CCNE
supervision: Pr. Emmanuel Didier, CMH/ENS/EHESS
output-ext: html
format:
  html:
    toc: true
    number-sections: true
    colorlinks: true
    geometry:
      - top=10mm
      - left=20mm
      - right=20mm
      - bottom=10mm  
      - heightrounded
    highlight-style: github
    fontfamily: libertinus
    documentclass: report
    fig-width: 12
    fig-height: 9
  pdf:
    documentclass: report
    papersize: a4
    toc: true
    toc-depth: 4
    number-sections: true
    number-depth: 3
    colorlinks: true
    fig-width: 20
    fig-height: 15
    keep-tex: false
execute:
  eval: true
  message: false
  warning: false
  echo: false
  output: true
  error: true
editor: source
---

```{r}
require(pacman,quietly = F)

pacman::p_load(arrow,
               tidyverse,
               reshape2,
               tibble,

               stats,
               rstatix,
               
               tokenizers,
               tidytext,

               ggplot2,
               gridExtra,
               ggprism,
               ggpubr,
               ggcorrplot,
               ComplexHeatmap,
               circlize,
               patchwork)

source("helpers/df_to_matrix.R")
source("helpers/heatmap.R")
source("helpers/lexico_helper.R")
source("helpers/figures.R")

save_figures = T
cutpoints = c(0, 1e-04, 0.001, 0.01, 0.05, 0.1, 1)
symbols = c("****", "***", "**", "*", "•","ns")
significance = c("p < 0.0001", "p < 0.001", "p < 0.01", "p < 0.05", "p < 0.1", "p>0.1")
signif_caption_text <- paste("Significance levels:\n", paste(symbols, ":", significance, collapse = ", "))

```

```{r}
annotations <- read.csv("../data/intermediate/current_annotation_file.csv")|>
  filter(!is.na(Personne))
annotations_count <- annotations|>
  mutate(text = sentence_text,
         label = Personne)|>
  unnest_tokens(word,text)|>
  anti_join(get_stopwords(language = "fr"), by = c("word" = "word"))|>
  count(label, word, sort = T)|>
  rename(word_count = n)|>
  bind_tf_idf(word, label, word_count)
    
```

```{r}
table(annotations$Personne)
```

```{r}
annotations_count|>
  ungroup()|>
  group_by(label)|>
  top_n(5, tf)|>
  ggplot(aes(word, tf, fill = label)) +
    geom_col(alpha = 0.8, show.legend = FALSE) +
    facet_wrap(~ label, scales = "free_y", ncol=2) +
    coord_flip() +
    scale_x_reordered() +
    labs(x = NULL, y = "Fréquence")+
  theme_ready()+
  theme(axis.text.y = element_text(size = 8))
```

```{r}
annotations_count|>
  ungroup()|>
  group_by(label)|>
  top_n(20, tf_idf)|>
  ggplot(aes(word, tf_idf, fill = label)) +
    geom_col(alpha = 0.8, show.legend = FALSE) +
    facet_wrap(~ label, scales = "free_y", ncol=2) +
    coord_flip() +
    scale_x_reordered() +
    labs(x = NULL, y = "Fréquence")+
  theme_ready()+
  theme(axis.text.y = element_text(size = 8))
```